new feature
evil-morfar/RCLootCouncil_Classic pull request #48
Opened 2022-12-10 10:23 UTC by Loogosh

new feature of auto-packing items by type from the selected list

2022-12-11 09:21 UTC, evil-morfar requested changes

2022-12-11 09:21 UTC, evil-morfar commented on API/OptionsUpdates.lua
> +									INVTYPE_HEAD = {
I would still like the new options to be grouped - `db.INVTYPE_HEAD` is not descriptive, so when anyone looks at it they'll have no idea what it is.

2022-12-11 09:21 UTC, evil-morfar commented on API/OptionsUpdates.lua
> +										name = "Head",
I'd very much like all text users see to be localized - most of these probably already exists in game (refer to https://www.townlong-yak.com/framexml/live/GlobalStrings.lua), but otherwise add them to `Locale/enUS.lua`.

2022-12-11 09:29 UTC, Loogosh commented on API/OptionsUpdates.lua
> +									INVTYPE_HEAD = {
> I would still like the new options to be grouped - `db.INVTYPE_HEAD` is not descriptive, so when anyone looks at it they'll have no idea what it is.

I don't quite understand what you mean by grouping db.INVTYPE_HEAD and what changes you want to get

2022-12-11 09:30 UTC, Loogosh commented on API/OptionsUpdates.lua
> +										name = "Head",
I'll do it well

2022-12-11 09:34 UTC, evil-morfar commented on API/OptionsUpdates.lua
> +									INVTYPE_HEAD = {
Take a look at how you consume the data in autopass - currently it lives in the "global" db table, i.e. `RCLootCouncil:Getdb().INVTYPE_HEAD` (I'll shorten the getdb part to just `db` from now on.

I'd like it to live in its own "namespace" i.e. `db.advancedAutopass.INVTYPE_HEAD` - that way we'll know what the "db variable" is for.

2022-12-11 09:43 UTC, Loogosh commented on API/OptionsUpdates.lua
> +									INVTYPE_HEAD = {
I don't really know how to work with tables, could you tell me how to do it, or point to the corresponding documentation, I understood the concept of the idea, but I don't know how to implement it

2022-12-11 09:50 UTC, evil-morfar commented on API/OptionsUpdates.lua
> +									INVTYPE_HEAD = {
Alright, I'll do it after you're done with the locales

2022-12-11 09:54 UTC, Loogosh commented on API/OptionsUpdates.lua
> +									INVTYPE_HEAD = {
thank you, I will definitely look at this solution, I will do local variables until tomorrow

2022-12-12 14:15 UTC, evil-morfar commented
Still need to test it in game, which I can't until thursday. Expect for the description, it's pretty much finished.

2022-12-12 14:15 UTC, evil-morfar approved these changes

2022-12-12 15:54 UTC, Loogosh commented
The code that I sent, I checked in the game, as soon as your revision is ready, write, I will test.

2022-12-12 21:05 UTC, Loogosh commented
after the raid, I noticed that not all loot is skipped, it is necessary to analyze about 5% is skipped

2022-12-20 06:27 UTC, Loogosh commented
have you never tested *?

2022-12-20 06:49 UTC, evil-morfar commented
No, I've been caught up in retail issues

2022-12-24 09:10 UTC, Loogosh commented
Is there any way I can help with this ?

2022-12-24 09:38 UTC, evil-morfar commented
Well you mentioned it didn't always work, so maybe look into that

2023-01-06 10:28 UTC, evil-morfar commented
Finally got some time to look into it. It's now in a state I'd merge.
I'll delay merging it to give you a chance to check it out - I won't be pushing a new classic version this week anyway.

2023-01-07 10:18 UTC, Loogosh commented
I filmed in the last raid which items passed through the lock, I think how to analyze them, should I send you a link to the video?

2023-01-07 19:00 UTC, evil-morfar commented
Sure

2023-01-08 08:37 UTC, Loogosh commented
https://www.pyypl.com/#section-download

here is the link in the settings I had that only ranged weapons should pass through the filter,
if necessary, I will translate all the items that were here

2023-01-08 10:24 UTC, evil-morfar commented
That is not a video link

2023-01-08 10:25 UTC, Loogosh commented
yes sory misklick

2023-01-08 10:43 UTC, evil-morfar commented
Are they BoE items?
Also, certain chest items are classified as `"INVTYPE_ROBE"` and we've only added `"INVTYPE_CHEST"` - requires a bit of manual work to combine them.

2023-01-08 10:56 UTC, Loogosh commented
Yes I think I've figured out what the error might be thanks I'll check

2023-01-19 11:45 UTC, merged